### ISSUE TITLE
Basic tweaks to work in windows

### ISSUE THREAD

**Issue by ignaciocaamanio** [nsceaux/lyqi#5]
It would be nice to find a way of generalize ´compile-ly´ and ´open-pdf´.
In file lyqi-compile-commands.el, line 60, the semicolon should be an ampersand to work in windows. 
Also lyqi:pdf-command could use the pdf reader avaible in the system, not just xpdf? 

Don't know yet how to do that, and how to colaborate in a github proyect, I appreciate any advice to guide me.

**Comment by nsceaux** [comment]
Oups, it seems I missed this comment.
It is possible to cumstomize these commands. For instance, to show the PDF with a dedicated viewer on mac, one could use the following configuration:
`(custom-set-variables
   '(lyqi:pdf-command "open -a Skim")`
So on windows, you might use something like that. Tou can also override the compile-ly command the variable lyqi:lilypond-command.

**Comment by ignacio-gc** [comment]
thanks, I'll do that !!
